In [15]:
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [80]:
true_labels_path = "Mg22_dw_data/Mg22_size512_test_labels.npy"
y_true = np.load(f'{true_labels_path}')

predictions_path = "predictions/54/Mg22_size512_predictions.npy"
y_predictions = np.load(f'{predictions_path}')

In [81]:
y_prediction_labels = np.argmax(y_predictions, axis=1)

accuracy = accuracy_score(y_true, y_prediction_labels)
print(f"Accuracy: {accuracy}")

Accuracy: 0.363


In [82]:
cm = confusion_matrix(y_true, y_prediction_labels)
print(cm)

[[488 261 202  41   9   0]
 [  4  10   5   3   1   0]
 [ 77 128 133 114  30   0]
 [ 75 158 133  95  30   0]
 [  0   0   1   0   0   0]
 [  1   0   0   0   1   0]]


In [83]:
report = classification_report(y_true, y_prediction_labels)
print(report)

              precision    recall  f1-score   support

         0.0       0.76      0.49      0.59      1001
         1.0       0.02      0.43      0.03        23
         2.0       0.28      0.28      0.28       482
         3.0       0.38      0.19      0.26       491
         4.0       0.00      0.00      0.00         1
         5.0       0.00      0.00      0.00         2

    accuracy                           0.36      2000
   macro avg       0.24      0.23      0.19      2000
weighted avg       0.54      0.36      0.43      2000



/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m