In [128]:
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [329]:
true_labels_path = "Mg22_dw_data/Mg22_size512_test_labels.npy"
y_true = np.load(f'{true_labels_path}')

predictions_path = "predictions/63/10/Mg22_size512_predictions.npy"
y_predictions = np.load(f'{predictions_path}')

In [330]:
y_prediction_labels = np.argmax(y_predictions, axis=1)

accuracy = accuracy_score(y_true, y_prediction_labels)
print(f"Accuracy: {accuracy}")

Accuracy: 0.163


In [331]:
cm = confusion_matrix(y_true, y_prediction_labels)
print(cm)

[[ 73 273 231 245 179   0]
 [  0   8   4   5   6   0]
 [  2 129 116 135 100   0]
 [  2 117 131 129 112   0]
 [  0   1   0   0   0   0]
 [  0   0   1   0   1   0]]


In [332]:
report = classification_report(y_true, y_prediction_labels)
print(report)

              precision    recall  f1-score   support

         0.0       0.95      0.07      0.14      1001
         1.0       0.02      0.35      0.03        23
         2.0       0.24      0.24      0.24       482
         3.0       0.25      0.26      0.26       491
         4.0       0.00      0.00      0.00         1
         5.0       0.00      0.00      0.00         2

    accuracy                           0.16      2000
   macro avg       0.24      0.15      0.11      2000
weighted avg       0.59      0.16      0.19      2000



/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m