In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

2024-10-31 22:53:38.203726: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-31 22:53:38.263550: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-31 22:53:39.155730: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
true_labels_path = "../data_processing/data/Mg22_size512_test_labels.npy"
y_true = np.load(f'{true_labels_path}')

predictions_path = "../training/benchmark_predictions/2174/1/Mg22_size512_predictions.npy"
y_predictions = np.load(f'{predictions_path}')

In [3]:
y_prediction_labels = np.argmax(y_predictions, axis=1)

accuracy = accuracy_score(y_true, y_prediction_labels)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9585


In [4]:
cm = confusion_matrix(y_true, y_prediction_labels)
print(cm)

[[980   0   6   0   0]
 [  0  16   7   0   0]
 [  0   0 455  57   0]
 [  0   0  12 466   0]
 [  1   0   0   0   0]]


In [5]:
report = classification_report(y_true, y_prediction_labels)
print(report)

              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00       986
         1.0       1.00      0.70      0.82        23
         2.0       0.95      0.89      0.92       512
         3.0       0.89      0.97      0.93       478
         5.0       0.00      0.00      0.00         1

    accuracy                           0.96      2000
   macro avg       0.77      0.71      0.73      2000
weighted avg       0.96      0.96      0.96      2000



/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/DAVIDSON/anzhu/.conda/envs/jupyter/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m